spring:
  profiles:
    active: dev
  application:
    name: ead-payment-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
      username: configserver
      password: 'ead123cs'
