server:
  port: 8086

spring:
  application:
    name: ead-payment-service
  output:
    ansi:
      enabled: Always

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
