spring:
  application:
    name: ead-payment-service
  output:
    ansi:
      enabled: Always
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
      username: configserver
      password: 'ead123cs'
